### ISSUE TITLE
No information if the Url don't have "origin" or "referer"

### ISSUE THREAD

**Issue by mitmplay** [mitm-proxy/mitm-play#1]
When crafting route rule, adding some url matcher in which belongs to third parties domain, sometime we don't know  that the domain don't have request headers of "origin" or "referer". if third parties domain don't have  the "origin" or "referer", it need to break into different route. 

proposed is 
* to have console log to show that the url  don't have the "origin" or "referer"   
* automatic add template route for url that don't have the "origin" or "referer"

**Comment by wharsojo** [comment]
no need to automatically add template route.
